dynaconf_merge = true

[tls]
# The paths to TLS cert and key the whole application should use for things.
# if these aren't set right, TLS won't engage.
certificate = "cert.pem"
key = "key.pem"

[postgresql]
dsn = "postgres://postgres:password@localhost:5432/phantasm"

[shared]
# The external IP address to bind to.
# This will be used for binding all of the portal's listening
# ports, and also the game's webserver.
external = "0.0.0.0"
# the class that'll be used to handle the launcher.
launcher = "mudforge.utils.Launcher"
# The name of the project.
name = "mudforge"


[portal.networking]
# The port that normal telnet will listen on. Set to 0 to disable.
telnet = 7000
# The port that secure telnet (TLS) will listen on. Set to 0 to disable.
telnets = 7001
# The port that SSH will listen on. Set to 0 to disable.
ssh = 0
# The Link will attempt to connect to this address after negotiations to connect to the game
# via SocketIO. It will also be provided to all webclients. So, it should be your external domain
# name/url or IP address.
game_url = "https://127.0.0.1:8000"

[portal.classes]
# The class that'll be used to handle the portal.
application = "mudforge.portal.application.Application"
telnet = "mudforge.portal.telnet.TelnetConnection"

[portal.services]
telnet = "mudforge.portal.telnet.TelnetService"
telnets = "mudforge.portal.telnet.TLSTelnetService"

[game]

[game.classes]
# The class that'll be used to handle the game.
application = "mudforge.game.application.Application"

[game.lockfuncs]
# The key is only used for overrides or disables. It loads all functions defined
# in the module which do not begin with an underscore.
base = "mudforge.game.locks.lockfuncs"

[game.networking]
# governs who is allowed to use X-Forwarded-For and have it respected.
trusted_proxy_ips = ["127.0.0.1"]
port = 8000

[game.commands]
boards = "mudforge.portal.commands.boards"
system = "mudforge.portal.commands.system"

[fastapi.routers]
# every module listed here must have a global named
# "router" to be imported.
auth = "mudforge.game.api.auth"
users = "mudforge.game.api.users"
characters = "mudforge.game.api.characters"
boards = "mudforge.game.api.boards"

[jwt]
algorithm = "HS256"
secret = "CHANGE_ME_DAMMIT"
token_expire_minutes = 30
# 7 days in minutes.
refresh_expire_minutes = 10080